kind: pipeline
name: default

steps:
  - name: docker
    image: plugins/docker
    settings:
      repo: docker.vatsimspain.es/formacion-vatspa/web
      registry: docker.vatsimspain.es/
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password